version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - db
    # networks:
    #   - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

volumes:
  db:
    driver: local
# networks:
#   postgres-network:
#     driver: bridge
